services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sigma_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLL_INTERVAL=1000
